title:              lbc_cn
email:              365324702@qq.com
description:        Software Engineer of Testing
author:             lbc
baseurl:            "/"
url:                "https://lbc-cn.github.io"

# Social Profiles
twitter_username:   lbc_cn
github_username:    lbc-cn
facebook_username:  lbc_cn
linkedin_username:  lbc_cn

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
